config/routes.rb
Online::Application.routes.draw do
  resources :questions

  resources :exams

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  
  attr_accessible :exam_code, :exam_type, :instruction, :name, :organisation_id, :subject, :total_mark
  
  has_many :examquestion
  has_many :questions, :through => :examquestion
end

app/models/examquestion.rb
class Examquestion < ActiveRecord::Base
  belongs_to :exam
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  attr_accessible :category_subject_id, :description, :feed_back, :is_published, :is_shared_boolean, :mark, :name, :parent_id, :question_type_id, :sort_order, :subject_id, :user_id
  
  has_many :examquestion
  has_many :exams, :through => :examquestion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exams }
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @exam = Exam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/new
  # GET /exams/new.json
  def new
    @exam = Exam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/1/edit
  def edit
    @exam = Exam.find(params[:id])
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(params[:exam])

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render json: @exam, status: :created, location: @exam }
      else
        format.html { render action: "new" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exams/1
  # PUT /exams/1.json
  def update
    @exam = Exam.find(params[:id])

    respond_to do |format|
      if @exam.update_attributes(params[:exam])
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :exam_code %><br />
    <%= f.text_field :exam_code %>
  </div>
  <div class="field">
    <%= f.label :instruction %><br />
    <%= f.text_area :instruction %>
  </div>
  <div class="field">
    <%= f.label :exam_type %><br />
    <%= f.text_field :exam_type %>
  </div>
  <div class="field">
    <%= f.label :total_mark %><br />
    <%= f.number_field :total_mark %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :organisation_id %><br />
    <%= f.number_field :organisation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<h1>Listing exams</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Exam code</th>
    <th>Instruction</th>
    <th>Exam type</th>
    <th>Total mark</th>
    <th>Subject</th>
    <th>Organisation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exams.each do |exam| %>
  <tr>
    <td><%= exam.name %></td>
    <td><%= exam.exam_code %></td>
    <td><%= exam.instruction %></td>
    <td><%= exam.exam_type %></td>
    <td><%= exam.total_mark %></td>
    <td><%= exam.subject %></td>
    <td><%= exam.organisation_id %></td>
    <td><%= link_to 'Show', exam %></td>
    <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
    <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exam.name %>
</p>

<p>
  <b>Exam code:</b>
  <%= @exam.exam_code %>
</p>

<p>
  <b>Instruction:</b>
  <%= @exam.instruction %>
</p>

<p>
  <b>Exam type:</b>
  <%= @exam.exam_type %>
</p>

<p>
  <b>Total mark:</b>
  <%= @exam.total_mark %>
</p>

<p>
  <b>Subject:</b>
  <%= @exam.subject %>
</p>

<p>
  <b>Organisation:</b>
  <%= @exam.organisation_id %>
</p>


<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :question_type_id %><br />
    <%= f.number_field :question_type_id %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :is_published %><br />
    <%= f.check_box :is_published %>
  </div>
  <div class="field">
    <%= f.label :is_shared %><br />
    <%= f.check_box :is_shared %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br />
    <%= f.number_field :subject_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :category_subject_id %><br />
    <%= f.number_field :category_subject_id %>
  </div>
  <div class="field">
    <%= f.label :mark %><br />
    <%= f.number_field :mark %>
  </div>
  <div class="field">
    <%= f.label :feed_back %><br />
    <%= f.number_field :feed_back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Question type</th>
    <th>Sort order</th>
    <th>Is published</th>
    <th>Is shared boolean</th>
    <th>User</th>
    <th>Subject</th>
    <th>Name</th>
    <th>Parent</th>
    <th>Category subject</th>
    <th>Mark</th>
    <th>Feed back</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.description %></td>
    <td><%= question.question_type_id %></td>
    <td><%= question.sort_order %></td>
    <td><%= question.is_published %></td>
    <td><%= question.is_shared %></td>
    <td><%= question.user_id %></td>
    <td><%= question.subject_id %></td>
    <td><%= question.name %></td>
    <td><%= question.parent_id %></td>
    <td><%= question.category_subject_id %></td>
    <td><%= question.mark %></td>
    <td><%= question.feed_back %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @question.description %>
</p>

<p>
  <b>Question type:</b>
  <%= @question.question_type_id %>
</p>

<p>
  <b>Sort order:</b>
  <%= @question.sort_order %>
</p>

<p>
  <b>Is published:</b>
  <%= @question.is_published %>
</p>

<p>
  <b>Is shared boolean:</b>
  <%= @question.is_shared %>
</p>

<p>
  <b>User:</b>
  <%= @question.user_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @question.subject_id %>
</p>

<p>
  <b>Name:</b>
  <%= @question.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @question.parent_id %>
</p>

<p>
  <b>Category subject:</b>
  <%= @question.category_subject_id %>
</p>

<p>
  <b>Mark:</b>
  <%= @question.mark %>
</p>

<p>
  <b>Feed back:</b>
  <%= @question.feed_back %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>